<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="27" passed="0" failed="0" skipped="27">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-06T16:11:13 IST" name="SmaZer_sanity" finished-at="2025-05-06T16:11:13 IST" duration-ms="116">
    <groups>
    </groups>
    <test started-at="2025-05-06T16:11:13 IST" name="Test" finished-at="2025-05-06T16:11:13 IST" duration-ms="116">
      <class name="smaZer_testcases.TC23_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC23_Analytics@6692b6c6]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:22, instance:smaZer_testcases.TC23_Analytics@6692b6c6]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC23_Analytics@6692b6c6]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC23_Analytics@6692b6c6]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC23_Analytics -->
      <class name="smaZer_testcases.TC02_SignUp">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC02_SignUp@6ea2bc93]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC02_SignUp@6ea2bc93]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUp()[pri:1, instance:smaZer_testcases.TC02_SignUp@6ea2bc93]" started-at="2025-05-06T16:11:13 IST" name="signUp" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC02_SignUp@6ea2bc93]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC02_SignUp -->
      <class name="smaZer_testcases.TC30_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC30_Schedular@50313382]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:29, instance:smaZer_testcases.TC30_Schedular@50313382]" started-at="2025-05-06T16:11:13 IST" name="schedule" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC30_Schedular@50313382]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC30_Schedular@50313382]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC30_Schedular -->
      <class name="smaZer_testcases.TC04_SignIn_Flow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC04_SignIn_Flow@f627d13]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC04_SignIn_Flow@f627d13]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signIn()[pri:3, instance:smaZer_testcases.TC04_SignIn_Flow@f627d13]" started-at="2025-05-06T16:11:13 IST" name="signIn" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC04_SignIn_Flow@f627d13]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC04_SignIn_Flow -->
      <class name="smaZer_testcases.TC34_smaZer_Info">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC34_smaZer_Info@4d518b32]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:33, instance:smaZer_testcases.TC34_smaZer_Info@4d518b32]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC34_smaZer_Info@4d518b32]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC34_smaZer_Info@4d518b32]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC34_smaZer_Info -->
      <class name="smaZer_testcases.TC14_BleWithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC14_BleWithRouter@463fd068]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC14_BleWithRouter@463fd068]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:13, instance:smaZer_testcases.TC14_BleWithRouter@463fd068]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC14_BleWithRouter@463fd068]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC14_BleWithRouter -->
      <class name="smaZer_testcases.TC03_SignUp">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC03_SignUp@3116c353]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC03_SignUp@3116c353]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUp()[pri:2, instance:smaZer_testcases.TC03_SignUp@3116c353]" started-at="2025-05-06T16:11:13 IST" name="signUp" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC03_SignUp@3116c353]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC03_SignUp -->
      <class name="smaZer_testcases.TC06_SignIn_SuccessFlow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC06_SignIn_SuccessFlow@352ff4da]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC06_SignIn_SuccessFlow@352ff4da]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:5, instance:smaZer_testcases.TC06_SignIn_SuccessFlow@352ff4da]" started-at="2025-05-06T16:11:13 IST" name="login" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC06_SignIn_SuccessFlow@352ff4da]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC06_SignIn_SuccessFlow -->
      <class name="smaZer_testcases.TC05_SignIn_Valid_User">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC05_SignIn_Valid_User@4e928fbf]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC05_SignIn_Valid_User@4e928fbf]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:4, instance:smaZer_testcases.TC05_SignIn_Valid_User@4e928fbf]" started-at="2025-05-06T16:11:13 IST" name="login" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC05_SignIn_Valid_User@4e928fbf]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC05_SignIn_Valid_User -->
      <class name="smaZer_testcases.TC32_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC32_Factory_Reset@4c012563]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC32_Factory_Reset@4c012563]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:31, instance:smaZer_testcases.TC32_Factory_Reset@4c012563]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC32_Factory_Reset@4c012563]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC32_Factory_Reset -->
      <class name="smaZer_testcases.TC25_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC25_Analytics@589da3f3]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:24, instance:smaZer_testcases.TC25_Analytics@589da3f3]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC25_Analytics@589da3f3]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC25_Analytics@589da3f3]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC25_Analytics -->
      <class name="smaZer_testcases.TC28_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC28_Schedular@6736fa8d]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC28_Schedular@6736fa8d]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="schedule()[pri:27, instance:smaZer_testcases.TC28_Schedular@6736fa8d]" started-at="2025-05-06T16:11:13 IST" name="schedule" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC28_Schedular@6736fa8d]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC28_Schedular -->
      <class name="smaZer_testcases.TC10_Pairing_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC10_Pairing_SmartConfig@3e44f2a5]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:9, instance:smaZer_testcases.TC10_Pairing_SmartConfig@3e44f2a5]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC10_Pairing_SmartConfig@3e44f2a5]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC10_Pairing_SmartConfig@3e44f2a5]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC10_Pairing_SmartConfig -->
      <class name="smaZer_testcases.TC19_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC19_DeviceSettings@651aed93]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:18, instance:smaZer_testcases.TC19_DeviceSettings@651aed93]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC19_DeviceSettings@651aed93]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC19_DeviceSettings@651aed93]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC19_DeviceSettings -->
      <class name="smaZer_testcases.TC33_Ble_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC33_Ble_Factory_Reset@14a50707]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC33_Ble_Factory_Reset@14a50707]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:32, instance:smaZer_testcases.TC33_Ble_Factory_Reset@14a50707]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC33_Ble_Factory_Reset@14a50707]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC33_Ble_Factory_Reset -->
      <class name="smaZer_testcases.TC29_Schedular">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC29_Schedular@52815fa3]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC29_Schedular@52815fa3]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:28, instance:smaZer_testcases.TC29_Schedular@52815fa3]" started-at="2025-05-06T16:11:13 IST" name="schedule" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC29_Schedular@52815fa3]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC29_Schedular -->
      <class name="smaZer_testcases.TC26_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC26_Analytics@39d76cb5]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC26_Analytics@39d76cb5]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:25, instance:smaZer_testcases.TC26_Analytics@39d76cb5]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC26_Analytics@39d76cb5]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC26_Analytics -->
      <class name="smaZer_testcases.Longrun_voltvalue">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:smaZer_testcases.Longrun_voltvalue@72ade7e3]" started-at="2025-05-06T16:11:13 IST" name="beforeSuite" finished-at="2025-05-06T16:11:13 IST" duration-ms="300" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:smaZer_testcases.Longrun_voltvalue@72ade7e3]" started-at="2025-05-06T16:11:13 IST" name="beforeTest" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:smaZer_testcases.Longrun_voltvalue@72ade7e3]" started-at="2025-05-06T16:11:13 IST" name="afterTest" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:smaZer_testcases.Longrun_voltvalue@72ade7e3]" started-at="2025-05-06T16:11:13 IST" name="afterSuite" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- smaZer_testcases.Longrun_voltvalue -->
      <class name="smaZer_testcases.TC09_Pairing_BlewithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC09_Pairing_BlewithRouter@748741cb]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC09_Pairing_BlewithRouter@748741cb]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:8, instance:smaZer_testcases.TC09_Pairing_BlewithRouter@748741cb]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC09_Pairing_BlewithRouter@748741cb]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC09_Pairing_BlewithRouter -->
      <class name="smaZer_testcases.TC24_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC24_Analytics@1cd629b3]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC24_Analytics@1cd629b3]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:23, instance:smaZer_testcases.TC24_Analytics@1cd629b3]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC24_Analytics@1cd629b3]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC24_Analytics -->
      <class name="smaZer_testcases.TC21_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC21_DeviceSettings@bb9e6dc]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:20, instance:smaZer_testcases.TC21_DeviceSettings@bb9e6dc]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC21_DeviceSettings@bb9e6dc]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC21_DeviceSettings@bb9e6dc]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC21_DeviceSettings -->
      <class name="smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@42b3b079]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:17, instance:smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@42b3b079]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@42b3b079]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@42b3b079]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03 -->
      <class name="smaZer_testcases.TC15_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC15_SmartConfig@895e367]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:14, instance:smaZer_testcases.TC15_SmartConfig@895e367]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC15_SmartConfig@895e367]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC15_SmartConfig@895e367]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC15_SmartConfig -->
      <class name="smaZer_testcases.TC08_Pairing_BlewithoutRouter">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC08_Pairing_BlewithoutRouter@2e32ccc5]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC08_Pairing_BlewithoutRouter@2e32ccc5]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:7, instance:smaZer_testcases.TC08_Pairing_BlewithoutRouter@2e32ccc5]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC08_Pairing_BlewithoutRouter@2e32ccc5]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC08_Pairing_BlewithoutRouter -->
      <class name="smaZer_testcases.TC20_DeviceSettings">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC20_DeviceSettings@4dd6fd0a]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC20_DeviceSettings@4dd6fd0a]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:19, instance:smaZer_testcases.TC20_DeviceSettings@4dd6fd0a]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC20_DeviceSettings@4dd6fd0a]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC20_DeviceSettings -->
      <class name="smaZer_testcases.TC07_SignIn_Logout">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC07_SignIn_Logout@3224a577]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC07_SignIn_Logout@3224a577]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:6, instance:smaZer_testcases.TC07_SignIn_Logout@3224a577]" started-at="2025-05-06T16:11:13 IST" name="login" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC07_SignIn_Logout@3224a577]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC07_SignIn_Logout -->
      <class name="smaZer_testcases.TC31_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC31_Schedular@1cb346ea]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC31_Schedular@1cb346ea]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="schedule()[pri:30, instance:smaZer_testcases.TC31_Schedular@1cb346ea]" started-at="2025-05-06T16:11:13 IST" name="schedule" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC31_Schedular@1cb346ea]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC31_Schedular -->
      <class name="smaZer_testcases.TC13_BlewithoutRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:smaZer_testcases.TC13_BlewithoutRouter@5f77d0f9]" started-at="2025-05-06T16:11:13 IST" name="startTestCase" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:12, instance:smaZer_testcases.TC13_BlewithoutRouter@5f77d0f9]" started-at="2025-05-06T16:11:13 IST" name="removerepair" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1028)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1015)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:smaZer_testcases.TC13_BlewithoutRouter@5f77d0f9]" started-at="2025-05-06T16:11:13 IST" name="beforeMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:smaZer_testcases.TC13_BlewithoutRouter@5f77d0f9]" started-at="2025-05-06T16:11:13 IST" name="afterMethod" finished-at="2025-05-06T16:11:13 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- smaZer_testcases.TC13_BlewithoutRouter -->
    </test> <!-- Test -->
  </suite> <!-- SmaZer_sanity -->
</testng-results>
